apiVersion: v1
kind: Service
metadata:
  name: mssql-headless-from-snapshot
  labels:
    app: mssql
spec:
  clusterIP: None
  selector:
    name: mssql-pod
  ports:
  - name: sql
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-from-snapshot
spec:
  ports:
  - name: mssql-port-from-snapshot
    port: 1433
    targetPort: 1433
  selector:
    name: mssql-pod-from-snapshot
  type: LoadBalancer